name: CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode:14"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build my Nodejs Docker image
        run: docker image build --tag="${IMAGE_NAME}" ./

      - name: Testing
        run: docker container run "${IMAGE_NAME}" npm test

      - name: Linting
        run: docker container run "${IMAGE_NAME}" npm run lint

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && needs.build.result == 'success'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: doublep3
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          tags: doublep3/nodejs_mongodb:latest